# Generated by Django 5.0 on 2025-03-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonentry',
            name='diet_meals',
        ),
        migrations.AddField(
            model_name='carbonentry',
            name='beef_meals',
            field=models.IntegerField(default=0, help_text='Number of beef-based meals'),
        ),
        migrations.AddField(
            model_name='carbonentry',
            name='chicken_meals',
            field=models.IntegerField(default=0, help_text='Number of chicken-based meals'),
        ),
        migrations.AddField(
            model_name='carbonentry',
            name='veg_meals',
            field=models.IntegerField(default=0, help_text='Number of vegetarian meals'),
        ),
    ]
