# Generated by Django 5.0 on 2025-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_carbonentry_end_lat_carbonentry_end_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonentry',
            name='end_lat',
            field=models.FloatField(blank=True, help_text='Ending latitude', null=True),
        ),
        migrations.AlterField(
            model_name='carbonentry',
            name='end_lng',
            field=models.FloatField(blank=True, help_text='Ending longitude', null=True),
        ),
        migrations.AlterField(
            model_name='carbonentry',
            name='start_lat',
            field=models.FloatField(blank=True, help_text='Starting latitude', null=True),
        ),
        migrations.AlterField(
            model_name='carbonentry',
            name='start_lng',
            field=models.FloatField(blank=True, help_text='Starting longitude', null=True),
        ),
    ]
