# Generated by Django 5.0 on 2025-03-05 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_carbonentry_end_lat_alter_carbonentry_end_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=1.7, help_text='Height in meters'),
        ),
        migrations.CreateModel(
            name='FitnessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(default=0, help_text='Weight in kg')),
                ('waist_size', models.FloatField(default=0, help_text='Waist size in cm')),
                ('exercise_minutes', models.IntegerField(default=0, help_text='Exercise time in minutes')),
                ('calories', models.IntegerField(default=0, help_text='Daily calorie intake')),
                ('bmi', models.FloatField(default=0, help_text='Calculated BMI')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
